### ISSUE TITLE
Recipient account should be created in case it does not exist for OutTransfer transaction

### ISSUE THREAD

**Issue by SargeKhan** [LiskArchive/lisk-elements#1222] opened 2019-04-12 09:48 UTC
### Expected behavior
Application should create a new account for recipient id if it does not exist in the database.
### Actual behavior
Application failed out transfer transaction which does not have an existing recipient in the database.

### Which version(s) does this affect? (Environment, OS, etc...)
Release/2.1.0

**Comment by shuse2** [comment] 2019-04-15 08:29
duplicate of #1220

**Closed as completed by shuse2** 2019-04-15 08:29 UTC
Labels: 🐛bug, lisk-transactions
